### ISSUE TITLE
Changing directory too fast causes race condition on static UpdateUI

### ISSUE THREAD

**Issue by noahc3** [SamPoulton/Explode#4]
Changing directories too fast (ex. spamming the back button) causes UpdateUI to be executed on multiple threads. Since UpdateUI is static, a race condition occurs where static variables (like index) are modified by multiple threads, causing the directory listing update to fail.

A solution could be to have one static update thread, and try to abort/cancel it as soon as CurrentDirectory is changed.

Edit: Example when it doesn't outright crash 

![](https://puu.sh/B5Z0y/cbda7bc30c.png)

This is an amalgamation of several different directories since several threads were updating the UI at the same time.

**Comment by SamPoulton** [comment]
Almost got a fix for this - give me a minute to finish it.
